### ISSUE TITLE
Roadmap Progress

### ISSUE THREAD

**Issue by njosefbeck** [njosefbeck/devops-and-backend-dev-roadmap#1]
The below todos are generated from the roadmaps for backend dev and devops. As I think they complement each other, and they both represent spheres of knowledge that I want to be intimately familiar with, I'm just creating one todo list.

As I complete each item I'll check it off. "Completeness" of an item is a bit subjective, but I'll judge something is complete when I have something tangible to show for that todo. Whether that's a program, a blog post, or something else, I will link to such "evidence" here.

## Roadmap Todos

- [x] Pick a language: Go
- [ ] Learn & practice what you've learned by building some command line apps
  - [ ]  gophercises
    - [x] [quiz](https://github.com/njosefbeck/gophercises/tree/master/quiz)
  - [x] [ehonnnavi.net web scraper](https://github.com/njosefbeck/ehonnavi-scraper)
  - [ ] aggregate and send self a daily email of hackernews and lobste.rs
  - [ ] aggregate and send self a daily email with google analytics data for all web properties
  - [ ] build a pretty command line interface for working with go processes
- [ ] Understand different OS concepts
  - [x] Process management (Evidence: [Notes](https://github.com/njosefbeck/devops-and-backend-dev-roadmap/issues/2), [Blog post](https://njosefbeck.com/what-is-a-process))
  - [ ] Threads and Concurrency
  - [ ] Sockets
  - [ ] I/O Management
  - [ ] Virtualization
  - [ ] Memory / Storage
  - [ ] File Systems
